version: "3.8"

services:
    api:
        environment:
          - ASPNETCORE_HTTPS_PORT=5001
          - ASPNETCORE_URLS=http://+:5001
        build:
          context: ./SupportDeskAPI
          dockerfile: Dockerfile
        ports:
          - "5001:5001"

    web:
        build:
          context: ./support-desk-web
          dockerfile: Dockerfile
        ports:
          - "3000:3000"
        depends_on:
          - api
        volumes:
          - ./support-desk-web/:/src/app/